apiVersion: 1
datasources:
  - name: AgentProbe PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: agentprobe
    user: agentprobe
    secureJsonData:
      password: agentprobe
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
